name: search_time_with_index
description: Bu package orqali siz uch xil search functionlaridan foydalana olasiz bular Binary seach LInery search Jump search. maybe it is best.
version: 1.0.0
homepage: https://github.com/Azamatjon17/search_time_with_index

environment:
  sdk: ^3.4.4

dependencies:
  # Add regular dependencies here.
  # For example:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
